[package]
name = "ommrema"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { version = "3.1.3", features = ["embed"] }
rust-embed = "8.5.0"
tokio = { version = "1.41.1", features = ["rt-multi-thread", "macros"] }
