name: backend-format

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - uses: actions/checkout@v4
    - name: Check rustfmt
      run: |
        cargo fmt -- --check
